services:
  - type: web
    name: idanplus-stremio-live
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PUBLIC_BASE_URL
        sync: false
      - key: IDANPLUS_REFRESH_SECONDS
        value: "300"
